-- ======================================================================
-- COGNI — COMBINED SUPABASE SETUP (setup.sql)
--
-- AUTO-GENERATED from the individual files in supabase/, in README order.
-- Do NOT edit this file directly — edit the modular files and regenerate.
-- Every section is idempotent, so this whole file is SAFE TO RE-RUN (e.g. to
-- sync an existing database to the latest schema).
--
-- PREREQUISITE (one manual step): enable Supabase Vault before running.
--   Dashboard → Database → Extensions → enable "supabase_vault",
--   OR uncomment the next line:
-- create extension if not exists supabase_vault;
-- ======================================================================


-- ======================================================================
-- SECTION 1. Core schema
-- ======================================================================

-- ----- schema.sql -----
-- ============================================================
-- COGNI — FULL DATABASE SCHEMA
-- Run this entire file in the Supabase SQL editor
-- Idempotent: safe to run more than once (create-if-not-exists + drop/create policies).
-- ============================================================

-- Enable pgvector for RAG embeddings
create extension if not exists vector;

-- ============================================================
-- TABLES
-- ============================================================

-- Users (extends Supabase auth.users)
create table if not exists public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  university text,
  major text,
  year text,
  session_length_preference integer not null default 45, -- minutes: 25, 45, or 90
  timezone text not null default 'UTC',
  created_at timestamptz not null default now()
);

-- Professors (independent entities, persist across semesters)
create table if not exists public.professors (
  professor_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  name text not null,
  department text,
  profile_status text not null default 'active' check (profile_status in ('active', 'archived')),
  created_at timestamptz not null default now()
);

-- Courses
create table if not exists public.courses (
  course_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  professor_id uuid references public.professors(professor_id) on delete set null,
  name text not null,
  department text,
  course_type text check (course_type in ('quantitative', 'conceptual_science', 'humanities', 'social_science', 'language', 'professional')),
  semester text,
  active_status text not null default 'active' check (active_status in ('active', 'archived')),
  created_at timestamptz not null default now()
);

-- Topics (created from syllabus, core of the four-number framework)
create table if not exists public.topics (
  topic_id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(course_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  name text not null,
  syllabus_order integer,
  content_coverage numeric(3,2) not null default 0 check (content_coverage >= 0 and content_coverage <= 1),
  professor_weight numeric(3,2) not null default 0.5 check (professor_weight >= 0 and professor_weight <= 1),
  -- Topic-level FSRS fields
  fsrs_stability numeric,
  fsrs_difficulty numeric,
  fsrs_next_review_date date,
  created_at timestamptz not null default now()
);

-- Topic Mastery (mastery score per topic per student)
create table if not exists public.topic_mastery (
  mastery_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  topic_id uuid not null references public.topics(topic_id) on delete cascade,
  mastery_score numeric(3,2) check (mastery_score >= 0 and mastery_score <= 1),
  confidence numeric(3,2) check (confidence >= 0 and confidence <= 1),
  last_updated timestamptz not null default now(),
  unique(user_id, topic_id)
);

-- Flashcards (card-level FSRS)
create table if not exists public.flashcards (
  card_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  course_id uuid not null references public.courses(course_id) on delete cascade,
  topic_id uuid references public.topics(topic_id) on delete set null,
  front text not null,
  back text not null,
  hint text,
  -- Card-level FSRS fields
  fsrs_stability numeric not null default 0,
  fsrs_difficulty numeric not null default 0,
  fsrs_retrievability numeric,
  fsrs_last_review timestamptz,
  fsrs_next_review_date date not null default current_date,
  fsrs_reps integer not null default 0,
  fsrs_lapses integer not null default 0,
  fsrs_state text not null default 'new' check (fsrs_state in ('new', 'learning', 'review', 'relearning')),
  created_at timestamptz not null default now()
);

-- Exams
create table if not exists public.exams (
  exam_id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(course_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  date date not null,
  grade_weight numeric(5,2), -- percentage of final grade
  topics_covered uuid[], -- array of topic_ids
  student_score numeric(5,2), -- nullable, populated when graded exam uploaded
  duration_minutes integer, -- from syllabus, used for simulated exam timer
  created_at timestamptz not null default now()
);

-- Assignments / Homework
create table if not exists public.assignments (
  assignment_id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(course_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  name text,
  due_date timestamptz not null,
  type text, -- homework, quiz, project, etc.
  completion_status text not null default 'pending' check (completion_status in ('pending', 'complete', 'late')),
  created_at timestamptz not null default now()
);

-- Materials (uploaded files and typed content)
create table if not exists public.materials (
  material_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  course_id uuid references public.courses(course_id) on delete set null,
  tier integer check (tier between 1 and 4),
  file_type text, -- pdf, txt, image, typed
  storage_path text, -- path in Supabase Storage materials bucket
  filename text,
  processing_status text not null default 'pending' check (processing_status in ('pending', 'processing', 'processed', 'failed')),
  uploaded_at timestamptz not null default now(),
  topic_ids uuid[] -- populated after processing
);

-- Inbox Items (raw classification queue)
create table if not exists public.inbox_items (
  inbox_item_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  material_id uuid references public.materials(material_id) on delete cascade,
  classification_status text not null default 'pending' check (classification_status in ('pending', 'classified', 'unassigned', 'failed')),
  confidence_score numeric(3,2) check (confidence_score >= 0 and confidence_score <= 1),
  course_id uuid references public.courses(course_id) on delete set null,
  tier integer check (tier between 1 and 4),
  nudge_pending boolean not null default false,
  created_at timestamptz not null default now()
);

-- Tutor Session Log
create table if not exists public.session_log (
  session_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  course_id uuid not null references public.courses(course_id) on delete cascade,
  name text, -- auto-generated by Haiku after first exchange
  mode text not null default 'answer' check (mode in ('answer', 'teach', 'focus', 'essay')),
  topics_discussed uuid[], -- array of topic_ids
  duration_seconds integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tutor Messages (per session)
create table if not exists public.session_messages (
  message_id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.session_log(session_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

-- Nudges
create table if not exists public.nudges (
  nudge_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  type text not null, -- homework_completion, material_gap, pending_classification, missing_api_key, missing_syllabus, calendar_conflict, upload_content
  tier text not null check (tier in ('critical', 'standard', 'recurring')),
  content text not null,
  course_id uuid references public.courses(course_id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'snoozed')),
  snoozed_until timestamptz, -- for standard nudges dismissed with 7-day cooldown
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

-- Wiki Versions (snapshot table for recovery)
create table if not exists public.wiki_versions (
  version_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  file_path text not null, -- e.g. 'learning_profile.md', 'professor_abc123.md'
  content text not null,
  triggered_by_agent text, -- inbox, profiler, tutor, etc.
  created_at timestamptz not null default now()
);

-- Study Plan (daily generated plan)
create table if not exists public.study_plan (
  plan_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  plan_date date not null,
  tasks jsonb not null default '[]', -- array of task objects with type, course_id, topic_ids, duration_minutes, order
  generated_at timestamptz not null default now(),
  unique(user_id, plan_date)
);

-- Mastery History (for 30-day trend lines in Progress tab)
create table if not exists public.mastery_history (
  history_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  topic_id uuid not null references public.topics(topic_id) on delete cascade,
  mastery_score numeric(3,2) not null,
  recorded_at timestamptz not null default now()
);

-- Vector Embeddings (RAG via pgvector)
create table if not exists public.material_embeddings (
  embedding_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  material_id uuid not null references public.materials(material_id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  embedding vector(1536), -- text-embedding-3-small dimension
  created_at timestamptz not null default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.users enable row level security;
alter table public.professors enable row level security;
alter table public.courses enable row level security;
alter table public.topics enable row level security;
alter table public.topic_mastery enable row level security;
alter table public.flashcards enable row level security;
alter table public.exams enable row level security;
alter table public.assignments enable row level security;
alter table public.materials enable row level security;
alter table public.inbox_items enable row level security;
alter table public.session_log enable row level security;
alter table public.session_messages enable row level security;
alter table public.nudges enable row level security;
alter table public.wiki_versions enable row level security;
alter table public.study_plan enable row level security;
alter table public.mastery_history enable row level security;
alter table public.material_embeddings enable row level security;

-- ============================================================
-- RLS POLICIES (all scoped to auth.uid())
-- drop-then-create so the file is re-runnable (CREATE POLICY has no IF NOT EXISTS)
-- ============================================================

-- Users
drop policy if exists "users: own row only" on public.users;
create policy "users: own row only" on public.users
  for all using (auth.uid() = user_id);

-- Professors
drop policy if exists "professors: own rows only" on public.professors;
create policy "professors: own rows only" on public.professors
  for all using (auth.uid() = user_id);

-- Courses
drop policy if exists "courses: own rows only" on public.courses;
create policy "courses: own rows only" on public.courses
  for all using (auth.uid() = user_id);

-- Topics
drop policy if exists "topics: own rows only" on public.topics;
create policy "topics: own rows only" on public.topics
  for all using (auth.uid() = user_id);

-- Topic Mastery
drop policy if exists "topic_mastery: own rows only" on public.topic_mastery;
create policy "topic_mastery: own rows only" on public.topic_mastery
  for all using (auth.uid() = user_id);

-- Flashcards
drop policy if exists "flashcards: own rows only" on public.flashcards;
create policy "flashcards: own rows only" on public.flashcards
  for all using (auth.uid() = user_id);

-- Exams
drop policy if exists "exams: own rows only" on public.exams;
create policy "exams: own rows only" on public.exams
  for all using (auth.uid() = user_id);

-- Assignments
drop policy if exists "assignments: own rows only" on public.assignments;
create policy "assignments: own rows only" on public.assignments
  for all using (auth.uid() = user_id);

-- Materials
drop policy if exists "materials: own rows only" on public.materials;
create policy "materials: own rows only" on public.materials
  for all using (auth.uid() = user_id);

-- Inbox Items
drop policy if exists "inbox_items: own rows only" on public.inbox_items;
create policy "inbox_items: own rows only" on public.inbox_items
  for all using (auth.uid() = user_id);

-- Session Log
drop policy if exists "session_log: own rows only" on public.session_log;
create policy "session_log: own rows only" on public.session_log
  for all using (auth.uid() = user_id);

-- Session Messages
drop policy if exists "session_messages: own rows only" on public.session_messages;
create policy "session_messages: own rows only" on public.session_messages
  for all using (auth.uid() = user_id);

-- Nudges
drop policy if exists "nudges: own rows only" on public.nudges;
create policy "nudges: own rows only" on public.nudges
  for all using (auth.uid() = user_id);

-- Wiki Versions
drop policy if exists "wiki_versions: own rows only" on public.wiki_versions;
create policy "wiki_versions: own rows only" on public.wiki_versions
  for all using (auth.uid() = user_id);

-- Study Plan
drop policy if exists "study_plan: own rows only" on public.study_plan;
create policy "study_plan: own rows only" on public.study_plan
  for all using (auth.uid() = user_id);

-- Mastery History
drop policy if exists "mastery_history: own rows only" on public.mastery_history;
create policy "mastery_history: own rows only" on public.mastery_history
  for all using (auth.uid() = user_id);

-- Material Embeddings
drop policy if exists "material_embeddings: own rows only" on public.material_embeddings;
create policy "material_embeddings: own rows only" on public.material_embeddings
  for all using (auth.uid() = user_id);

-- ============================================================
-- INDEXES (performance) — named + if-not-exists so re-runs are safe
-- ============================================================

create index if not exists idx_topics_course_id on public.topics(course_id);
create index if not exists idx_topic_mastery_user_topic on public.topic_mastery(user_id, topic_id);
create index if not exists idx_flashcards_user_course on public.flashcards(user_id, course_id);
create index if not exists idx_flashcards_due on public.flashcards(fsrs_next_review_date);
create index if not exists idx_exams_course_date on public.exams(course_id, date);
create index if not exists idx_assignments_user_due on public.assignments(user_id, due_date);
create index if not exists idx_nudges_user_status on public.nudges(user_id, status);
create index if not exists idx_session_log_user_course on public.session_log(user_id, course_id);
create index if not exists idx_mastery_history_user_topic_recorded on public.mastery_history(user_id, topic_id, recorded_at);
-- The ivfflat index build needs more working memory than the Supabase free tier's
-- default maintenance_work_mem (32MB). Raise it just for this build, then restore.
-- Without this, free-tier setup aborts here with:
--   ERROR: 54000: memory required is N MB, maintenance_work_mem is 32 MB
-- and every object defined later in this script is silently left uncreated.
set maintenance_work_mem = '128MB';
create index if not exists idx_material_embeddings_embedding on public.material_embeddings using ivfflat (embedding vector_cosine_ops);
reset maintenance_work_mem;


-- ======================================================================
-- SECTION 2. Vault (requires the Vault extension — see header)
-- ======================================================================

-- ----- vault-helpers.sql -----
-- Run this in the Supabase SQL editor after enabling Vault.
-- Creates public-schema wrappers so service-role API routes can store user-scoped secrets by name.

create or replace function store_user_secret(p_user_id uuid, p_secret_name text, p_secret text)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  secret_name text := 'user_secret_' || p_user_id::text || '_' || p_secret_name;
  existing_id uuid;
begin
  if p_secret_name !~ '^[a-z0-9_]+$' then
    raise exception 'Invalid secret name';
  end if;

  select id into existing_id from vault.secrets where name = secret_name;

  if existing_id is not null then
    perform vault.update_secret(existing_id, p_secret, secret_name, 'Cogni user secret');
  else
    perform vault.create_secret(p_secret, secret_name, 'Cogni user secret');
  end if;
end;
$$;

create or replace function store_user_api_key(p_user_id uuid, p_key text)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  secret_name text := 'api_key_' || p_user_id::text;
  existing_id uuid;
begin
  select id into existing_id from vault.secrets where name = secret_name;

  if existing_id is not null then
    perform vault.update_secret(existing_id, p_key, secret_name, 'User AI API key');
  else
    perform vault.create_secret(p_key, secret_name, 'User AI API key');
  end if;
end;
$$;

-- Grant execute to authenticated role so API routes using service key can call it
grant execute on function store_user_secret(uuid, text, text) to service_role;
grant execute on function store_user_api_key(uuid, text) to service_role;


-- ----- vault-get.sql -----
-- Run this in the Supabase SQL editor to enable API key retrieval.

create or replace function get_user_secret(p_user_id uuid, p_secret_name text)
returns text
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  v_secret text;
begin
  if p_secret_name !~ '^[a-z0-9_]+$' then
    raise exception 'Invalid secret name';
  end if;

  select decrypted_secret into v_secret
  from vault.decrypted_secrets
  where name = 'user_secret_' || p_user_id::text || '_' || p_secret_name;
  return v_secret;
end;
$$;

create or replace function get_user_api_key(p_user_id uuid)
returns text
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  v_key text;
begin
  select decrypted_secret into v_key
  from vault.decrypted_secrets
  where name = 'api_key_' || p_user_id::text;
  return v_key;
end;
$$;

grant execute on function get_user_api_key(uuid) to service_role;
grant execute on function get_user_secret(uuid, text) to service_role;


-- ======================================================================
-- SECTION 3. Storage buckets
-- ======================================================================

-- ----- storage-buckets.sql -----
-- Storage buckets required by Cogni.
-- Run in Supabase SQL editor after schema.sql.
-- The course-files bucket is created separately in course-files.sql.

-- ── materials ─────────────────────────────────────────────────────────────────
-- Uploaded PDFs, text files, and syllabuses.
-- All paths are stored as {user_id}/{filename} in the materials table.
insert into storage.buckets (id, name, public)
values ('materials', 'materials', false)
on conflict (id) do nothing;

drop policy if exists "materials: owner upload" on storage.objects;
create policy "materials: owner upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'materials' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "materials: owner read" on storage.objects;
create policy "materials: owner read" on storage.objects
  for select to authenticated
  using (bucket_id = 'materials' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "materials: owner delete" on storage.objects;
create policy "materials: owner delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'materials' and auth.uid()::text = (storage.foldername(name))[1]);

-- ── wiki ──────────────────────────────────────────────────────────────────────
-- Markdown knowledge files (learning profile, professor profiles).
-- Paths: {user_id}/{filename}.md
insert into storage.buckets (id, name, public)
values ('wiki', 'wiki', false)
on conflict (id) do nothing;

drop policy if exists "wiki: owner upload" on storage.objects;
create policy "wiki: owner upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'wiki' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "wiki: owner read" on storage.objects;
create policy "wiki: owner read" on storage.objects
  for select to authenticated
  using (bucket_id = 'wiki' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "wiki: owner delete" on storage.objects;
create policy "wiki: owner delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'wiki' and auth.uid()::text = (storage.foldername(name))[1]);

-- ── audio ─────────────────────────────────────────────────────────────────────
-- Generated audio overview MP3s (TTS).
-- Paths: {user_id}/{filename}.mp3
insert into storage.buckets (id, name, public)
values ('audio', 'audio', false)
on conflict (id) do nothing;

drop policy if exists "audio: owner upload" on storage.objects;
create policy "audio: owner upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'audio' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "audio: owner read" on storage.objects;
create policy "audio: owner read" on storage.objects
  for select to authenticated
  using (bucket_id = 'audio' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "audio: owner delete" on storage.objects;
create policy "audio: owner delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'audio' and auth.uid()::text = (storage.foldername(name))[1]);


-- ----- course-files.sql -----
-- ============================================================
-- COGNI — Course File Storage
-- Run in Supabase SQL editor after schema.sql
-- ============================================================

-- Table: tracks files attached to a course
create table if not exists public.course_files (
  file_id     uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  course_id   uuid not null references public.courses(course_id) on delete cascade,
  name        text not null,          -- original filename
  mime_type   text not null,
  size_bytes  bigint not null,
  storage_path text not null,         -- path in Supabase Storage bucket
  created_at  timestamptz not null default now()
);

-- RLS
alter table public.course_files enable row level security;

drop policy if exists "owner_all" on public.course_files;
create policy "owner_all" on public.course_files
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Index for fast per-course lookups
create index if not exists course_files_course_id_idx on public.course_files (course_id);

-- ============================================================
-- Storage bucket (run via Supabase dashboard or this SQL)
-- ============================================================
-- In the Supabase dashboard → Storage → New bucket:
--   Name: course-files
--   Public: OFF (private)
-- Then add RLS policies on storage.objects:

insert into storage.buckets (id, name, public)
values ('course-files', 'course-files', false)
on conflict (id) do nothing;

-- Allow authenticated users to upload/read/delete their own files
drop policy if exists "owner_upload" on storage.objects;
create policy "owner_upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'course-files' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "owner_read" on storage.objects;
create policy "owner_read" on storage.objects
  for select to authenticated
  using (bucket_id = 'course-files' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "owner_delete" on storage.objects;
create policy "owner_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'course-files' and auth.uid()::text = (storage.foldername(name))[1]);


-- ======================================================================
-- SECTION 4. Additional tables
-- ======================================================================

-- ----- calendar-connections.sql -----
-- Run in Supabase SQL Editor (Phase 11 — Calendar Integration)

create table if not exists public.calendar_connections (
  connection_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  provider text not null check (provider in ('google', 'apple', 'outlook')),
  access_token text, -- deprecated; secrets are stored in Supabase Vault
  refresh_token text, -- deprecated; secrets are stored in Supabase Vault
  expires_at timestamptz,
  cogni_calendar_id text, -- ID of the "Cogni Study" calendar created by us
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, provider)
);

alter table public.calendar_connections enable row level security;

drop policy if exists "calendar_connections: own rows only" on public.calendar_connections;
create policy "calendar_connections: own rows only" on public.calendar_connections
  for all using (auth.uid() = user_id);


-- ----- practice-test-results.sql -----
-- Practice test results — run in Supabase SQL editor
create table if not exists public.practice_test_results (
  result_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  course_id uuid not null references public.courses(course_id) on delete cascade,
  test_type text not null check (test_type in ('practice_quiz', 'simulated_exam')),
  topic_filter text,            -- topic name if user filtered to one topic
  question_count integer not null,
  correct_count integer not null default 0,
  score_pct numeric(5,2),       -- 0–100
  missed_topics jsonb default '[]'::jsonb,   -- [{topic, wrong_count}]
  mastery_updates jsonb default '[]'::jsonb, -- [{topic_id, topic_name, old_score, new_score}]
  duration_seconds integer,     -- simulated exam only
  created_at timestamptz not null default now()
);

alter table public.practice_test_results enable row level security;

drop policy if exists "Users manage own practice results" on public.practice_test_results;
create policy "Users manage own practice results"
  on public.practice_test_results
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ----- course-web-suggestions.sql -----
-- Stores web-searched syllabus/course content surfaced to the user for approval.
-- Fires automatically on course creation when no syllabus is uploaded.

create table if not exists public.course_web_suggestions (
  id           uuid        primary key default gen_random_uuid(),
  course_id    uuid        not null references public.courses(course_id) on delete cascade,
  user_id      uuid        not null references auth.users(id) on delete cascade,
  title        text,
  url          text,
  content      text        not null,
  status       text        not null default 'pending'
               check (status in ('pending', 'approved', 'dismissed')),
  created_at   timestamptz not null default now()
);

alter table public.course_web_suggestions enable row level security;

drop policy if exists "Users manage their own web suggestions" on public.course_web_suggestions;
create policy "Users manage their own web suggestions"
  on public.course_web_suggestions
  for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ----- user-keys.sql -----
-- Generic per-user key store (metadata only).
-- Secret values are stored encrypted in Supabase Vault (see vault-helpers.sql);
-- key_value is nullable because plaintext secrets are migrated out via
-- user-keys-vault-migration.sql. New writes never store plaintext here.
CREATE TABLE IF NOT EXISTS user_keys (
  user_id  UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  key_name TEXT NOT NULL,
  key_value TEXT,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, key_name)
);

-- Idempotent: relax legacy NOT NULL on existing deployments so plaintext can be removed.
ALTER TABLE user_keys ALTER COLUMN key_value DROP NOT NULL;

ALTER TABLE user_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own keys" ON user_keys;
CREATE POLICY "Users manage their own keys"
  ON user_keys FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- ======================================================================
-- SECTION 5. Schema migrations (columns added after initial schema)
-- ======================================================================

-- ----- course-icon.sql -----
-- Add icon and icon_color columns to courses
alter table public.courses add column if not exists icon text;
alter table public.courses add column if not exists icon_color text default 'blue';


-- ----- essay-content.sql -----
-- Add essay content persistence to session_log
-- Run in Supabase SQL editor
alter table public.session_log add column if not exists essay_content text;


-- ----- session-inline-card.sql -----
-- Add inline_card column to session_messages to persist artifact payloads
-- (flashcards, quiz questions, essay open events) so they survive session reload.
alter table public.session_messages
  add column if not exists inline_card jsonb;


-- ----- streak-columns.sql -----
-- Add streak tracking to users table
alter table public.users
  add column if not exists study_streak integer not null default 0,
  add column if not exists last_study_date date;


-- ----- inbox-unreadable-status.sql -----
-- Adds 'unreadable' as a valid classification_status for inbox_items.
-- Used when a file (e.g. image-only PDF) cannot be read by text extraction
-- or Anthropic vision, so the user can assign it manually.
ALTER TABLE inbox_items DROP CONSTRAINT IF EXISTS inbox_items_classification_status_check;
ALTER TABLE inbox_items ADD CONSTRAINT inbox_items_classification_status_check
  CHECK (classification_status IN ('pending', 'classified', 'unassigned', 'failed', 'unreadable'));


-- ----- tutor-rate-limit.sql -----
-- Phase 24: daily tutor message rate limit
-- Adds an optional per-user daily message cap for the Tutor.
-- null = no limit (default).

alter table public.users
  add column if not exists daily_message_limit integer;


-- ----- user-timezone.sql -----
alter table public.users
  add column if not exists timezone text not null default 'UTC';


-- ----- calendar-token-vault-migration.sql -----
-- Move Google Calendar tokens out of public.calendar_connections and into Supabase Vault.
-- Run after vault-helpers.sql and vault-get.sql.

alter table public.calendar_connections
  alter column access_token drop not null;

comment on column public.calendar_connections.access_token is
  'Deprecated. Token secrets are stored in Vault under google_calendar_access_token.';

comment on column public.calendar_connections.refresh_token is
  'Deprecated. Token secrets are stored in Vault under google_calendar_refresh_token.';

update public.calendar_connections
set access_token = null,
    refresh_token = null
where provider = 'google';


-- ======================================================================
-- SECTION 6. Functions and indexes
-- ======================================================================

-- ----- fsrs-review-rpc.sql -----
-- Atomic FSRS + topic mastery update. Replaces the two-step write in
-- /api/cards/review/route.ts so a partial failure can't leave the card
-- marked reviewed without bumping mastery (or vice versa).
--
-- SECURITY DEFINER is required so the function can update topic_mastery
-- across users while still letting a logged-in caller invoke it. The
-- explicit user_id check in the WHERE clause is what enforces the
-- per-user boundary; do not remove it.

-- Drop the old (buggy) signature if it exists. The first revision of this file
-- declared p_fsrs_state as integer, but flashcards.fsrs_state is a text column
-- with a CHECK ('new','learning','review','relearning'), and the route passes
-- a string. The integer signature made every call fail 500.
drop function if exists public.review_card_atomic(
  uuid, uuid, numeric, numeric, integer, integer, integer, timestamptz, date, numeric
);

-- Unified mastery model (F3): the additive-delta signature is replaced by
-- evidence (observed level + learning rate) applied as an EWMA — the SAME rule
-- lib/mastery.ts uses for tutor grades and quizzes, so all three writers move
-- the score on one scale. Drop the old signatures.
drop function if exists public.review_card_atomic(
  uuid, uuid, numeric, numeric, integer, integer, text, timestamptz, date, numeric
);
drop function if exists public.review_card_atomic(
  uuid, uuid, numeric, numeric, integer, integer, text, timestamptz, date, numeric, numeric
);

-- One row per card rating (B6 idempotency gate + the substrate for per-user FSRS
-- optimization, I4). client_review_id is generated by the client per rating: a
-- retried/replayed POST carries the same id and is dropped by ON CONFLICT,
-- so the FSRS update + mastery evidence apply exactly once.
create table if not exists public.review_logs (
  log_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  card_id uuid not null references public.flashcards(card_id) on delete cascade,
  client_review_id uuid not null unique,
  rating smallint not null check (rating between 1 and 4),
  prev_stability numeric,
  prev_difficulty numeric,
  prev_state text,
  new_stability numeric,
  new_difficulty numeric,
  new_state text,
  next_review_date date,
  reviewed_at timestamptz not null default now()
);
alter table public.review_logs enable row level security;
drop policy if exists "review_logs: own rows only" on public.review_logs;
create policy "review_logs: own rows only" on public.review_logs
  for select using (auth.uid() = user_id);
create index if not exists idx_review_logs_user_reviewed on public.review_logs(user_id, reviewed_at);

create or replace function public.review_card_atomic(
  p_card_id uuid,
  p_user_id uuid,
  p_fsrs_stability numeric,
  p_fsrs_difficulty numeric,
  p_fsrs_reps integer,
  p_fsrs_lapses integer,
  p_fsrs_state text,
  p_fsrs_last_review timestamptz,
  p_fsrs_next_review_date date,
  p_observed numeric,         -- 0..1: what this rating says the student's level is
  p_learning_rate numeric,    -- how far to move toward it (pre-scaled by deck size)
  p_rating smallint,          -- the raw 1-4 rating (logged for the FSRS optimizer)
  p_client_review_id uuid     -- idempotency key; null = legacy client, no dedup
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_card record;
begin
  -- Lock the card first: serializes concurrent duplicates and captures the
  -- pre-review FSRS state for the log.
  select card_id, topic_id, fsrs_stability, fsrs_difficulty, fsrs_state
  into v_card
  from public.flashcards
  where card_id = p_card_id and user_id = p_user_id
  for update;

  if not found then
    raise exception 'card not found or not owned by user';
  end if;

  -- Idempotency gate (B6): a duplicate client_review_id means this exact rating
  -- was already applied — return without touching FSRS or mastery. The previous
  -- behavior re-applied the mastery delta and re-advanced FSRS on every replay.
  insert into public.review_logs (
    user_id, card_id, client_review_id, rating,
    prev_stability, prev_difficulty, prev_state,
    new_stability, new_difficulty, new_state, next_review_date
  ) values (
    p_user_id, p_card_id, coalesce(p_client_review_id, gen_random_uuid()), p_rating,
    v_card.fsrs_stability, v_card.fsrs_difficulty, v_card.fsrs_state,
    p_fsrs_stability, p_fsrs_difficulty, p_fsrs_state, p_fsrs_next_review_date
  )
  on conflict (client_review_id) do nothing;

  if not found then
    return; -- duplicate submission — already applied exactly once
  end if;

  update public.flashcards
  set fsrs_stability = p_fsrs_stability,
      fsrs_difficulty = p_fsrs_difficulty,
      fsrs_reps = p_fsrs_reps,
      fsrs_lapses = p_fsrs_lapses,
      fsrs_state = p_fsrs_state,
      fsrs_last_review = p_fsrs_last_review,
      fsrs_next_review_date = p_fsrs_next_review_date
  where card_id = p_card_id
    and user_id = p_user_id;

  if v_card.topic_id is not null then
    -- EWMA toward the observed level: next = old + lr * (observed - old).
    -- Cold start (no row): adopt observed directly — the prior is uninformative.
    -- confidence grows +0.05 per evidence event (was a dead column, always 0).
    insert into public.topic_mastery (user_id, topic_id, mastery_score, confidence, last_updated)
    values (p_user_id, v_card.topic_id, greatest(0, least(1, p_observed)), 0.05, now())
    on conflict (user_id, topic_id) do update
      set mastery_score = greatest(0, least(1,
            coalesce(public.topic_mastery.mastery_score, 0)
            + greatest(0, least(1, p_learning_rate))
              * (greatest(0, least(1, p_observed)) - coalesce(public.topic_mastery.mastery_score, 0)))),
          confidence = least(1, coalesce(public.topic_mastery.confidence, 0) + 0.05),
          last_updated = now();

    insert into public.mastery_history (user_id, topic_id, mastery_score)
    select user_id, topic_id, mastery_score
    from public.topic_mastery
    where user_id = p_user_id
      and topic_id = v_card.topic_id;
  end if;
end;
$$;

-- service_role ONLY (was also granted to authenticated): the function is
-- SECURITY DEFINER and takes p_user_id as a parameter, so any logged-in user
-- could have replayed it against another user's card_id/user_id. Only the
-- server route calls it, via the service client.
grant execute on function public.review_card_atomic(
  uuid, uuid, numeric, numeric, integer, integer, text, timestamptz, date, numeric, numeric, smallint, uuid
) to service_role;


-- ----- rag-functions.sql -----
-- RAG vector similarity search function
-- Run in Supabase SQL Editor before using Phase 17 RAG features.

create or replace function match_material_chunks(
  p_user_id    uuid,
  p_course_id  uuid,
  p_query_embedding vector(1536),
  p_top_k      integer default 5
)
returns table (
  material_id  uuid,
  chunk_index  integer,
  content      text
)
language sql
stable
as $$
  select
    me.material_id,
    me.chunk_index,
    me.content
  from material_embeddings me
  join materials m on m.material_id = me.material_id
  where me.user_id = p_user_id
    and m.course_id = p_course_id
    and me.embedding is not null
  order by me.embedding <=> p_query_embedding
  limit p_top_k;
$$;

grant execute on function match_material_chunks(uuid, uuid, vector, integer) to service_role;


-- ----- vault-delete.sql -----
-- Run this in the Supabase SQL editor after vault-helpers.sql.
-- Adds delete wrappers so service-role API routes can permanently remove user-scoped
-- secrets (key removal on DELETE, account deletion, calendar disconnect) instead of
-- blanking them to an empty string. Safe to run more than once.

create or replace function delete_user_secret(p_user_id uuid, p_secret_name text)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  secret_name text := 'user_secret_' || p_user_id::text || '_' || p_secret_name;
begin
  if p_secret_name !~ '^[a-z0-9_]+$' then
    raise exception 'Invalid secret name';
  end if;

  delete from vault.secrets where name = secret_name;
end;
$$;

create or replace function delete_user_api_key(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
declare
  secret_name text := 'api_key_' || p_user_id::text;
begin
  delete from vault.secrets where name = secret_name;
end;
$$;

grant execute on function delete_user_secret(uuid, text) to service_role;
grant execute on function delete_user_api_key(uuid) to service_role;


-- ----- rag-keyword-index.sql -----
-- RAG keyword fallback full-text index.
-- Run in the Supabase SQL editor after schema.sql (and rag-functions.sql).
--
-- The keyword fallback in lib/rag.ts runs a plain text search against
-- public.material_embeddings.content, which Postgres executes as
--   content @@ plainto_tsquery('english', ...).
-- Without an index this is a sequential scan that recomputes to_tsvector per
-- row. This GIN index on to_tsvector('english', content) lets the planner use
-- the index, making the keyword fallback scalable for larger material sets.
--
-- Idempotent: CREATE INDEX IF NOT EXISTS is a no-op on re-run. The tsvector
-- config ('english') must match the config pinned in lib/rag.ts so the
-- expression index is usable by the query.

create index if not exists material_embeddings_content_fts
  on public.material_embeddings
  using gin (to_tsvector('english', content));


-- ======================================================================
-- SECTION 7. One-time data backfills and migrations
-- ======================================================================

-- ----- content-coverage-backfill.sql -----
-- Backfill topics.content_coverage based on existing flashcard counts.
-- Coverage = min(1.0, card_count / 10). Run once after deploying the flashcard
-- agent change that writes coverage on insert. Safe to re-run: deterministic.

update public.topics t
set content_coverage = least(
  1.0,
  (
    select count(*)::numeric / 10
    from public.flashcards f
    where f.topic_id = t.topic_id
  )
);


-- ----- user-keys-vault-migration.sql -----
-- One-time migration: move any plaintext per-user secrets still held in
-- public.user_keys (e.g. OpenAI keys set before Vault storage was added) into the
-- Vault, then remove the plaintext rows. Idempotent: once rows are migrated and
-- deleted, re-running is a no-op. Requires vault-helpers.sql to be applied first.

do $$
declare
  r record;
begin
  for r in
    select user_id, key_name, key_value
    from public.user_keys
    where key_value is not null
      and key_value <> ''
      and key_name ~ '^[a-z0-9_]+$'
  loop
    -- Store under the same name the app reads via get_user_secret().
    perform public.store_user_secret(r.user_id, r.key_name, r.key_value);
    -- Drop the plaintext copy now that the Vault holds it.
    delete from public.user_keys
    where user_id = r.user_id and key_name = r.key_name;
  end loop;
end $$;


-- ======================================================================
-- SECTION 8. Hosted multi-tenant security hardening
-- ======================================================================

-- ----- security-hardening.sql -----
-- ============================================================
-- HOSTED MULTI-TENANT SECURITY HARDENING (Phase 0)
-- Run after the rest of the schema. Idempotent / safe to re-run.
-- Required before opening public sign-up.
-- ============================================================

-- ── 1. Lock down exposed SECURITY DEFINER RPCs ───────────────
-- These functions are SECURITY DEFINER and take a caller-supplied user_id with
-- NO internal auth.uid() check, and they are reachable via the public Data API
-- (PostgREST) by anyone holding the public anon key. Postgres grants EXECUTE to
-- PUBLIC by default, so without these REVOKEs any visitor can decrypt every
-- user's API keys (get_user_*) or rewrite another user's flashcard state
-- (review_card_atomic). The app only ever calls them with the service-role
-- client, which retains EXECUTE, so revoking from anon/authenticated/public is
-- safe and closes the hole.

revoke execute on function public.get_user_api_key(uuid)                         from anon, authenticated, public;
revoke execute on function public.get_user_secret(uuid, text)                    from anon, authenticated, public;
revoke execute on function public.store_user_api_key(uuid, text)                 from anon, authenticated, public;
revoke execute on function public.store_user_secret(uuid, text, text)            from anon, authenticated, public;
revoke execute on function public.delete_user_api_key(uuid)                      from anon, authenticated, public;
revoke execute on function public.delete_user_secret(uuid, text)                 from anon, authenticated, public;
revoke execute on function public.review_card_atomic(uuid, uuid, numeric, numeric, integer, integer, text, timestamptz, date, numeric)
                                                                                 from anon, authenticated, public;

-- Re-assert that only the service role (used by all server routes) can call them.
grant execute on function public.get_user_api_key(uuid)                          to service_role;
grant execute on function public.get_user_secret(uuid, text)                     to service_role;
grant execute on function public.store_user_api_key(uuid, text)                  to service_role;
grant execute on function public.store_user_secret(uuid, text, text)             to service_role;
grant execute on function public.delete_user_api_key(uuid)                       to service_role;
grant execute on function public.delete_user_secret(uuid, text)                  to service_role;
grant execute on function public.review_card_atomic(uuid, uuid, numeric, numeric, integer, integer, text, timestamptz, date, numeric)
                                                                                 to service_role;

-- ── 2. Explicit WITH CHECK on all 18 user-scoped policies ────
-- PostgreSQL already falls back to the USING expression as the implicit
-- WITH CHECK, so this is defense-in-depth: it makes the INSERT/UPDATE row
-- constraint explicit instead of relying on the engine default. ALTER POLICY
-- preserves the existing USING clause and is idempotent.

alter policy "users: own row only" on public.users with check (auth.uid() = user_id);
alter policy "professors: own rows only" on public.professors with check (auth.uid() = user_id);
alter policy "courses: own rows only" on public.courses with check (auth.uid() = user_id);
alter policy "topics: own rows only" on public.topics with check (auth.uid() = user_id);
alter policy "topic_mastery: own rows only" on public.topic_mastery with check (auth.uid() = user_id);
alter policy "flashcards: own rows only" on public.flashcards with check (auth.uid() = user_id);
alter policy "exams: own rows only" on public.exams with check (auth.uid() = user_id);
alter policy "assignments: own rows only" on public.assignments with check (auth.uid() = user_id);
alter policy "materials: own rows only" on public.materials with check (auth.uid() = user_id);
alter policy "inbox_items: own rows only" on public.inbox_items with check (auth.uid() = user_id);
alter policy "session_log: own rows only" on public.session_log with check (auth.uid() = user_id);
alter policy "session_messages: own rows only" on public.session_messages with check (auth.uid() = user_id);
alter policy "nudges: own rows only" on public.nudges with check (auth.uid() = user_id);
alter policy "wiki_versions: own rows only" on public.wiki_versions with check (auth.uid() = user_id);
alter policy "study_plan: own rows only" on public.study_plan with check (auth.uid() = user_id);
alter policy "mastery_history: own rows only" on public.mastery_history with check (auth.uid() = user_id);
alter policy "material_embeddings: own rows only" on public.material_embeddings with check (auth.uid() = user_id);
alter policy "calendar_connections: own rows only" on public.calendar_connections with check (auth.uid() = user_id);

-- ── 3. Unique constraints behind the de-dup logic ───────────
-- onboarding/complete dedupes professors/courses by name (select-then-insert =
-- TOCTOU), and courses/create inserts a professor unconditionally (duplicates
-- on every course-create). These unique indexes make the dedup race-safe and
-- let the routes use upsert-on-conflict.
-- A unique index can't be created while duplicate (user_id, name) rows exist —
-- which a project predating this constraint may have. So de-dupe first (keep one
-- row per group). Duplicates are already invalid under the app's model (it
-- upserts on user_id+name), so this is a correct reconciliation, not data loss.
-- Without this, the index silently fails to create on a reused DB and the
-- onboarding/course-create upserts then 500 with "no unique constraint matching
-- the ON CONFLICT specification."
delete from public.professors a using public.professors b
  where a.user_id = b.user_id and a.name = b.name and a.ctid < b.ctid;
delete from public.courses a using public.courses b
  where a.user_id = b.user_id and a.name = b.name and a.ctid < b.ctid;
create unique index if not exists professors_user_name_uniq on public.professors (user_id, name);
create unique index if not exists courses_user_name_uniq    on public.courses (user_id, name);

-- Topics: same TOCTOU race as professors/courses — two concurrent profiler runs
-- read the same existing-topics snapshot and both insert the same "new" topic
-- (verified bug B12; the earlier unique-index pass covered professors/courses but
-- not topics). Consolidate duplicates first: repoint children to the kept row
-- (oldest), then delete the dupes, then index. flashcards.topic_id is ON DELETE
-- SET NULL and mastery_history is ON DELETE CASCADE, so deleting without
-- repointing would orphan cards and erase history.
create temp table _topic_dups as
select t.topic_id as dup_id, k.topic_id as keep_id
from public.topics t
join lateral (
  select topic_id from public.topics k
  where k.user_id = t.user_id and k.course_id = t.course_id and lower(k.name) = lower(t.name)
  order by k.created_at asc, k.topic_id asc
  limit 1
) k on true
where k.topic_id <> t.topic_id;

update public.flashcards f set topic_id = d.keep_id from _topic_dups d where f.topic_id = d.dup_id;
update public.mastery_history h set topic_id = d.keep_id from _topic_dups d where h.topic_id = d.dup_id;
delete from public.topic_mastery tm using _topic_dups d where tm.topic_id = d.dup_id;
delete from public.topics t using _topic_dups d where t.topic_id = d.dup_id;
drop table _topic_dups;

create unique index if not exists topics_user_course_name_uniq
  on public.topics (user_id, course_id, name);

-- Assignments: profiler re-runs with drifting names accrete duplicates; the
-- in-code dedup is per-run only (B12). Keep one row per (user, course, name, due_date).
delete from public.assignments a using public.assignments b
  where a.user_id = b.user_id and a.course_id = b.course_id
    and lower(coalesce(a.name, '')) = lower(coalesce(b.name, '')) and a.due_date = b.due_date
    and a.ctid < b.ctid;

create unique index if not exists assignments_user_course_name_due_uniq
  on public.assignments (user_id, course_id, name, due_date);

-- Tell PostgREST (the Supabase Data API layer the app's upsert-on-conflict goes
-- through) to reload its schema cache so it recognizes the unique indexes just
-- created. Without this, supabase-js upsert({ onConflict: 'user_id,name' }) keeps
-- failing with "no unique constraint matching the ON CONFLICT specification" even
-- though the index exists — until the cache reloads. Harmless no-op on a plain
-- Postgres with no PostgREST listening on the channel.
notify pgrst, 'reload schema';

-- ======================================================================
-- SECTION 9. Usage limits / abuse guards
-- ======================================================================

-- ----- usage-limits.sql -----
-- ============================================================
-- USAGE LIMITS / ABUSE GUARDS (hosted multi-tenant)
-- Daily per-user caps on expensive AI routes + an account suspend flag.
-- Idempotent / safe to re-run.
-- ============================================================

-- Per-user, per-action, per-day counter.
create table if not exists public.daily_usage (
  user_id uuid not null references public.users(user_id) on delete cascade,
  action  text not null,
  day     date not null default current_date,
  count   int  not null default 0,
  primary key (user_id, action, day)
);

alter table public.daily_usage enable row level security;
drop policy if exists "daily_usage: own rows only" on public.daily_usage;
create policy "daily_usage: own rows only" on public.daily_usage
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Atomic "increment and check" — returns true if still within the limit.
-- SECURITY DEFINER + service-role only (called from server routes), consistent
-- with the rest of the hardened RPCs.
create or replace function public.consume_daily_quota(p_user_id uuid, p_action text, p_limit int)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  insert into public.daily_usage (user_id, action, day, count)
  values (p_user_id, p_action, current_date, 1)
  on conflict (user_id, action, day) do update set count = public.daily_usage.count + 1
  returning count into v_count;
  return v_count <= p_limit;
end;
$$;

revoke execute on function public.consume_daily_quota(uuid, text, int) from anon, authenticated, public;
grant  execute on function public.consume_daily_quota(uuid, text, int) to service_role;

-- Account suspend flag (abuse response). Checked by the AI routes.
alter table public.users add column if not exists suspended boolean not null default false;

-- ============================================================================
-- 10. Production hardening — consent/age audit, runtime app-config (kill-switch),
--     signup gating, abuse/operator audit log, daily_usage retention.
--     Idempotent / safe to re-run. Run last (after sections 1–9).
-- ============================================================================

-- ── 10a. Consent + age audit on users ──────────────────────────────────────
-- Recorded server-side at signup (see /api/auth/signup). Append-only audit:
-- never cleared, so you can prove what version a user accepted and when.
alter table public.users add column if not exists tos_version       text;
alter table public.users add column if not exists tos_accepted_at   timestamptz;
alter table public.users add column if not exists privacy_version   text;
alter table public.users add column if not exists age_attested_at   timestamptz;

-- ── 10b. Runtime app config (singleton) — instant kill-switch, no redeploy ──
-- One row, read by lib/app-config.ts with a short in-process cache. Flip these
-- from the SQL editor (or the operator route) to pause signups / disable AI /
-- change the signup gate WITHOUT a redeploy.
create table if not exists public.app_config (
  id                   boolean primary key default true,
  signups_paused       boolean not null default false,   -- block all new signups
  ai_disabled          boolean not null default false,   -- hard-stop every AI route
  signup_mode          text    not null default 'open',  -- 'open' | 'invite' | 'edu'
  allowed_email_domains text[] not null default '{}',    -- for signup_mode='edu' (e.g. {'edu'} or {'mit.edu'})
  updated_at           timestamptz not null default now(),
  constraint app_config_singleton check (id = true),
  constraint app_config_signup_mode_chk check (signup_mode in ('open','invite','edu'))
);
insert into public.app_config (id) values (true) on conflict (id) do nothing;

alter table public.app_config enable row level security;
-- No anon/authenticated policy → RLS denies them by default. Only service_role
-- (which bypasses RLS) reads/writes it. Explicit revoke for defense in depth.
revoke all on public.app_config from anon, authenticated;

-- ── 10c. Invite codes (for signup_mode='invite') ───────────────────────────
-- Single-use codes consumed atomically by consume_invite_code() at signup.
create table if not exists public.invite_codes (
  code       text primary key,
  created_at timestamptz not null default now(),
  used_at    timestamptz,
  used_by    uuid,
  note       text
);
-- used_by is a plain uuid (no FK): the gating trigger sets it during the signup
-- transaction BEFORE the auth.users row exists, so an FK to auth.users(id) would
-- fail; and an audit column is better off surviving user deletion anyway. Drop
-- the FK if an earlier version created it.
alter table public.invite_codes drop constraint if exists invite_codes_used_by_fkey;
alter table public.invite_codes enable row level security;
revoke all on public.invite_codes from anon, authenticated;

-- Atomically claim an unused code. Returns true if claimed, false if missing/used.
-- SECURITY DEFINER + service-role only (called from the server signup route).
create or replace function public.consume_invite_code(p_code text, p_email text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ok boolean;
begin
  update public.invite_codes
     set used_at = now(), note = coalesce(note,'') || ' email:' || coalesce(p_email,'')
   where code = p_code and used_at is null
  returning true into v_ok;
  return coalesce(v_ok, false);
end;
$$;
revoke all      on function public.consume_invite_code(text, text) from anon, authenticated, public;
grant  execute  on function public.consume_invite_code(text, text) to service_role;

-- ── 10d. Abuse / operator audit log ─────────────────────────────────────────
-- Append-only record of security-relevant events for an operator to review:
-- suspensions, blocked signups, moderation blocks, data exports, etc.
create table if not exists public.audit_log (
  id              bigint generated always as identity primary key,
  created_at      timestamptz not null default now(),
  actor           text not null,            -- 'system' | 'operator' | a user_id
  action          text not null,            -- e.g. 'suspend_user','signup_blocked','moderation_block','data_export'
  subject_user_id uuid,
  detail          jsonb not null default '{}'::jsonb
);
create index if not exists audit_log_subject_idx on public.audit_log (subject_user_id, created_at desc);
create index if not exists audit_log_action_idx  on public.audit_log (action, created_at desc);
alter table public.audit_log enable row level security;
revoke all on public.audit_log from anon, authenticated;

-- ── 10e. Operator: suspend / unsuspend (audited) ────────────────────────────
-- Called by /api/operator/* (gated behind OPERATOR_SECRET). SECURITY DEFINER so
-- it can update users + write the audit row atomically; service-role only.
create or replace function public.operator_set_suspended(p_user_id uuid, p_suspended boolean, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.users set suspended = p_suspended where user_id = p_user_id;
  insert into public.audit_log (actor, action, subject_user_id, detail)
  values ('operator', case when p_suspended then 'suspend_user' else 'unsuspend_user' end,
          p_user_id, jsonb_build_object('reason', coalesce(p_reason,'')));
end;
$$;
revoke all     on function public.operator_set_suspended(uuid, boolean, text) from anon, authenticated, public;
grant  execute on function public.operator_set_suspended(uuid, boolean, text) to service_role;

-- ── 10f. daily_usage retention ──────────────────────────────────────────────
-- The abuse counter grows one row per (user, action, day) forever. Purge rows
-- older than 30 days. Called weekly by the maintenance cron (vercel.json).
create or replace function public.purge_old_daily_usage()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  delete from public.daily_usage where day < (current_date - interval '30 days');
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;
revoke all     on function public.purge_old_daily_usage() from anon, authenticated, public;
grant  execute on function public.purge_old_daily_usage() to service_role;

-- ── 10g. Signup gating ENFORCED at the database layer ───────────────────────
-- A BEFORE INSERT trigger on auth.users applies gating (signups_paused / invite
-- / edu) and atomic invite consumption to EVERY signup path — the server route,
-- a direct anon supabase.auth.signUp from the browser, AND Google OAuth — so it
-- cannot be bypassed client-side. It runs in the signup transaction, so a failed
-- signup rolls back any invite consumption (no more burned codes on failure).
create or replace function public.enforce_signup_policy()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cfg public.app_config;
  v_email   text := lower(coalesce(NEW.email, ''));
  v_domain  text;
  v_code    text;
  v_claimed boolean;
begin
  select * into cfg from public.app_config where id is true;
  if not found then
    return NEW; -- section 10 not configured → behave as open (self-host/single-tenant)
  end if;

  if cfg.signups_paused then
    raise exception 'signups_paused' using errcode = 'check_violation';
  end if;

  if cfg.signup_mode = 'edu' then
    v_domain := split_part(v_email, '@', 2);
    if v_domain = '' or not exists (
      select 1 from unnest(cfg.allowed_email_domains) d
      where v_domain = lower(replace(d, '*.', ''))
         or v_domain like '%.' || lower(replace(d, '*.', ''))
    ) then
      raise exception 'email_not_allowed' using errcode = 'check_violation';
    end if;
  elsif cfg.signup_mode = 'invite' then
    v_code := NEW.raw_user_meta_data->>'invite_code';
    if v_code is null or v_code = '' then
      raise exception 'invite_required' using errcode = 'check_violation';
    end if;
    update public.invite_codes
       set used_at = now(), used_by = NEW.id,
           note = coalesce(note, '') || ' email:' || v_email
     where code = v_code and used_at is null
    returning true into v_claimed;
    if not coalesce(v_claimed, false) then
      raise exception 'invalid_invite' using errcode = 'check_violation';
    end if;
  end if;

  return NEW;
end;
$$;

drop trigger if exists enforce_signup_policy_trg on auth.users;
create trigger enforce_signup_policy_trg
  before insert on auth.users
  for each row execute function public.enforce_signup_policy();

-- ── 10h. GDPR export: catalog lookup via SQL ────────────────────────────────
-- information_schema is not reachable through PostgREST, so the export route
-- discovers user-scoped tables via this SECURITY DEFINER RPC instead.
create or replace function public.list_user_scoped_tables()
returns setof text
language sql
security definer
set search_path = public
as $$
  select c.table_name
  from information_schema.columns c
  join information_schema.tables t
    on t.table_schema = c.table_schema and t.table_name = c.table_name
  where c.table_schema = 'public'
    and c.column_name = 'user_id'
    and t.table_type = 'BASE TABLE';
$$;
revoke all     on function public.list_user_scoped_tables() from anon, authenticated, public;
grant  execute on function public.list_user_scoped_tables() to service_role;


-- ======================================================================
-- Section 11: MCP — "bring your own Claude" connector
-- ======================================================================
-- Per-user bearer tokens for the Cogni MCP server (a user connects their own Claude
-- client to Cogni and tools are scoped to their data). Only the SHA-256 hash is
-- stored, never the plaintext token.
-- user_id is the PRIMARY KEY → at most one active token per user (regenerating
-- atomically replaces it). token_hash is uniquely indexed for the auth lookup.
create table if not exists public.mcp_tokens (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  token_hash text not null unique,
  label      text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  expires_at timestamptz
);
alter table public.mcp_tokens enable row level security;
-- No policies: only the server (service role) reads/writes these; RLS denies anon/authenticated.

-- Token expiry (F4): new tokens get created_at + 180 days; NULL = legacy token,
-- still honored until regenerated.
alter table public.mcp_tokens add column if not exists expires_at timestamptz;

-- Opt-in: route the in-app Tutor tab to the user's own Claude (via MCP) instead of
-- the built-in BYOK-API tutor.
alter table public.users add column if not exists prefer_own_claude boolean not null default false;

-- Per-invocation audit of MCP tool calls (F4): the MCP surface previously logged
-- nothing, so abuse or breakage was invisible. Service-role only (RLS, no policies).
create table if not exists public.mcp_tool_calls (
  call_id    uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  tool       text not null,
  ok         boolean not null,
  detail     text,
  created_at timestamptz not null default now()
);
alter table public.mcp_tool_calls enable row level security;
create index if not exists idx_mcp_tool_calls_user_created on public.mcp_tool_calls(user_id, created_at);

notify pgrst, 'reload schema';
